---
name: Run tests

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.4
        with:
          cli: latest
      - name: Run tests
        run: clojure -X:test
