---
name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          cli: latest

      - name: Build jar
        run: clojure -T:build build :git-version $(printf '"%s"'  $(git describe --tags))

      - name: Release to clojars
        continue-on-error: true
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -T:build deploy
