---
name: Test, build and (possibly) deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          cli: latest

      - name: Test, build and (possibly) deploy to clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: clojure -T:build release :git-version $(printf '"%s"'  $(git describe --tags)) :deploy/only-jar-version-type :full-and-snapshot
